import { Search, Sparkles } from "lucide-react";
import { useEffect, useId, useRef, useState } from "react";

import { Button } from "@/components/atoms/Button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/atoms/Card";
import { api } from "@/api/client";
import { cn } from "@/lib/cn";
import { MarkdownLite } from "@/lib/markdown";
import { BarChart } from "@/components/organisms/BarChart";
import { PieChart } from "@/components/organisms/PieChart";
import { chartForQuery } from "@/lib/chartFromQuery";
import type { GeometryResponse, QueryResponse } from "@/api/types";

interface Props {
  drawingKey?: string | null;
  /** Dynamic recommendations from the summary agent — when present
   * they replace the static per-drawing example chips. */
  suggestedQueries?: ReadonlyArray<{ label: string; text: string }>;
  /** Called when the user clicks a source citation. Optional — when not
   * provided, source citations stay informational only. */
  onSelectSource?: (drawingId: string, tag: string) => void;
  /** True once the current drawing has been analysed (live Run done OR
   * cached replay done OR a pre-built pipeline exists in the SearchIndex).
   * When false the input/Ask button/chips are disabled with a hint —
   * we don't want answers grounded in *other* drawings' indexes. */
  runReady?: boolean;
  /** Current drawing geometry — used to render an inline chart for
   * count/distribution questions. Optional; no chart when absent. */
  geometry?: GeometryResponse | null;
  /** When true, post-Run indexing of this drawing failed — queries still
   * work via the global fallback but grounding may be weaker. */
  indexWarning?: boolean;
}

export function QueryPanel({
  drawingKey, suggestedQueries, onSelectSource, runReady = false,
  geometry = null, indexWarning = false,
}: Props) {
  // Only show recommendations after a Run finishes — these are
  // generated by the summary agent from the actual extraction. Before
  // that we keep the chip area empty (with a one-line hint) so the
  // user isn't tempted to ask questions over an un-indexed drawing.
  const examples = suggestedQueries ?? [];
  const hasRecs = examples.length > 0;
  const inputId = useId();
  const [text, setText] = useState("");
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<QueryResponse | null>(null);

  // Clear chat state whenever the user picks a different drawing OR the
  // current drawing is re-Run (which causes summary chips to swap to a
  // fresh set). Both signals are observable from the props: drawingKey
  // changes for selection; suggestedQueries identity changes per Run.
  const prevDrawingRef = useRef<string | null | undefined>(drawingKey);
  const prevSuggestionsRef = useRef<typeof suggestedQueries>(suggestedQueries);
  // Request sequence: a query response only applies if it's still the
  // latest one. Bumped on drawing/suggestion change so an older
  // /api/query reply can't populate the newly-selected drawing.
  const querySeqRef = useRef(0);
  const mountedRef = useRef(true);
  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; querySeqRef.current++; };
  }, []);
  useEffect(() => {
    const drawingChanged = prevDrawingRef.current !== drawingKey;
    const recsChanged = prevSuggestionsRef.current !== suggestedQueries;
    if (drawingChanged || recsChanged) {
      querySeqRef.current++; // invalidate in-flight queries
      setText("");
      setError(null);
      setResult(null);
      prevDrawingRef.current = drawingKey;
      prevSuggestionsRef.current = suggestedQueries;
    }
  }, [drawingKey, suggestedQueries]);

  const submit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    void runQuery(text);
  };

  const runQuery = async (q: string) => {
    const query = q.trim();
    if (!query) return;
    const mySeq = ++querySeqRef.current;
    const fresh = () => mountedRef.current && querySeqRef.current === mySeq;
    setText(query);
    setPending(true);
    setError(null);
    try {
      // Restrict retrieval to the currently-selected drawing so the
      // answer never cites tags from another drawing.
      const r = await api.query({
        query,
        top_k: 6,
        drawing_filter: drawingKey ?? null,
      });
      if (!fresh()) return; // drawing changed mid-flight — drop stale reply
      setResult(r);
    } catch (err) {
      if (!fresh()) return;
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      if (fresh()) setPending(false);
    }
  };

  return (
    <Card className="flex h-full min-h-0 flex-col">
      <CardHeader>
        <CardTitle>Natural-Language Query</CardTitle>
        <span className="text-xs text-fg-muted">Sonnet 4.6</span>
      </CardHeader>
      <CardBody className="flex min-h-0 flex-1 flex-col gap-3">
        {indexWarning ? (
          <p className="rounded-md border border-warning/40 bg-warning/10 px-2.5 py-1.5 text-xs text-warning">
            이 도면의 인덱싱이 완료되지 않아 답변 정확도가 떨어질 수 있습니다.
          </p>
        ) : null}
        <form onSubmit={submit} className="flex items-center gap-2">
          <label htmlFor={inputId} className="sr-only">
            Ask a question about the indexed P&amp;ID drawings
          </label>
          <div className="relative flex-1">
            <Search
              aria-hidden
              className="absolute left-3 top-1/2 -translate-y-1/2 text-fg-muted"
              size={16}
            />
            <input
              id={inputId}
              type="text"
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder={
                runReady
                  ? "예: V-101을 보호하는 PSV를 알려줘"
                  : "도면을 먼저 분석(Run)해 주세요"
              }
              disabled={!runReady}
              aria-disabled={!runReady}
              className="h-10 w-full rounded-md border border-border-default bg-surface pl-9 pr-3 text-sm text-fg-primary placeholder:text-fg-muted focus-visible:border-accent focus-visible:outline-none disabled:cursor-not-allowed disabled:bg-canvas disabled:text-fg-muted"
            />
          </div>
          <Button
            type="submit"
            size="md"
            disabled={!runReady || pending || !text.trim()}
          >
            {pending ? "Asking…" : "Ask"}
          </Button>
        </form>

        <div className="flex flex-wrap items-center gap-1.5">
          <Sparkles aria-hidden className="text-accent" size={12} />
          {!runReady ? (
            <span className="text-[10px] uppercase tracking-wide text-fg-muted">
              도면을 선택한 뒤 좌측 캔버스의 Run 을 실행하면 자연어 질의가 활성화됩니다.
            </span>
          ) : hasRecs ? (
            <span className="text-[10px] uppercase tracking-wide text-accent">
              추천 (분석 결과 기반):
            </span>
          ) : (
            <span className="text-[10px] uppercase tracking-wide text-fg-muted">
              Run 완료 후 도면별 추천 질의가 여기 표시됩니다.
            </span>
          )}
          {runReady && examples.map((ex) => (
            <button
              key={ex.text}
              type="button"
              disabled={pending}
              onClick={() => void runQuery(ex.text)}
              className={cn(
                "rounded-full border border-border-default bg-surface px-2.5 py-0.5 text-xs text-fg-secondary",
                "hover:bg-raised hover:text-fg-primary",
                "disabled:cursor-not-allowed disabled:opacity-50",
                "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent",
              )}
            >
              {ex.label}
            </button>
          ))}
        </div>

        <div
          className="min-h-0 flex-1 overflow-y-scroll pr-2 [scrollbar-gutter:stable]"
          aria-live="polite"
        >
          {error ? (
            <p className="text-sm text-danger">Query failed: {error}</p>
          ) : result ? (
            <div className="flex flex-col gap-3">
              {(() => {
                const spec = chartForQuery(result.query ?? text, geometry);
                if (!spec) return null;
                return spec.kind === "pie" ? (
                  <PieChart title={spec.title} slices={spec.bars} unit={spec.unit} />
                ) : (
                  <BarChart title={spec.title} bars={spec.bars} unit={spec.unit} />
                );
              })()}
              <MarkdownLite text={result.answer} />
              {result.sources.length > 0 ? (
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-fg-muted">
                    Sources
                  </p>
                  <ul className="mt-1 flex flex-wrap gap-2 text-xs" role="list">
                    {result.sources.map((s, i) => (
                      <li key={`${s.drawing_id}-${s.tag}-${i}`}>
                        <button
                          type="button"
                          onClick={() => onSelectSource?.(s.drawing_id, s.tag)}
                          disabled={!onSelectSource}
                          aria-label={`Highlight ${s.tag} on drawing ${s.drawing_id}`}
                          className={cn(
                            "rounded-md border border-border-default px-2 py-1 font-mono",
                            onSelectSource
                              ? "text-fg-secondary hover:border-accent hover:bg-[var(--accent-soft)] hover:text-fg-primary"
                              : "cursor-default text-fg-muted",
                            "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent",
                          )}
                        >
                          {s.drawing_id} / {s.kind} / {s.tag}
                          <span className="ml-1 text-fg-muted">
                            ({s.score.toFixed(2)})
                          </span>
                        </button>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}
            </div>
          ) : (
            <p className="text-sm text-fg-muted">
              한국어 또는 영어로 질문하세요. 인덱싱된 도면만 근거로 답변합니다.
            </p>
          )}
        </div>
      </CardBody>
    </Card>
  );
}
