#!/usr/bin/env python3
"""CDK app entry point.

Two stacks:
  - PnidDemoNetwork: VPC + endpoints (stateful, terminationProtection ON)
  - PnidDemoApp: ECR + ECS Fargate + ALB + CloudFront (data plane)

cdk-nag (AwsSolutionsChecks) is wired up so synth fails if a serious
best-practice rule is violated. Suppressions live next to the resource
that triggers them with explicit reasons — never blanket-applied.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "infra" / "cdk"))

import aws_cdk as cdk
from cdk_nag import AwsSolutionsChecks, NagSuppressions

from app.app_stack import AppStack
from app.auth_stack import AuthStack
from app.network_stack import NetworkStack
from app.showcase_stack import ShowcaseStack

ACCOUNT = os.environ.get("CDK_DEFAULT_ACCOUNT") or os.environ.get("CDK_ACCOUNT")
REGION = os.environ.get("CDK_DEFAULT_REGION", "us-east-1")
ENV = cdk.Environment(account=ACCOUNT, region=REGION) if ACCOUNT else None

BEDROCK_MODELS = (
    "global.anthropic.claude-opus-4-8",
    "global.anthropic.claude-sonnet-4-6",
    "us.cohere.embed-v4:0",
)

app = cdk.App()

EXISTING_VPC_ID = os.environ.get("PNID_DEMO_VPC_ID")

if EXISTING_VPC_ID:
    # Reuse path: skip the NetworkStack and let AppStack look up the
    # given VPC. Avoids hitting the account's VPC/EIP quota when those
    # caps are already used by other projects.
    network = None
else:
    network = NetworkStack(
        app,
        "PnidDemoNetwork",
        env=ENV,
        termination_protection=True,
        tags={"project": "pnid-demo", "tier": "network"},
    )

auth = AuthStack(
    app,
    "PnidDemoAuth",
    env=ENV,
    # Callback URL is the eventual CloudFront distribution hostname.
    # We don't know it yet at synth time, but Cognito accepts a list and
    # the L@E function reads the actual distribution host from the
    # request — we just need at least one syntactically valid HTTPS URL
    # registered. After first deploy, append the real domain via
    # `cdk deploy` round 2 (see README) or update via the console.
    callback_urls=[os.environ.get(
        "CALLBACK_URL", "https://example.invalid/__auth/callback"
    )],
    tags={"project": "pnid-demo", "tier": "auth"},
)

# Hosted UI domain is "<prefix>.auth.<region>.amazoncognito.com".
hosted_ui_domain = (
    f"{auth.user_pool_domain.domain_name}.auth.{REGION}.amazoncognito.com"
)

app_stack = AppStack(
    app,
    "PnidDemoApp",
    env=ENV,
    vpc=network.vpc if network else None,
    existing_vpc_id=EXISTING_VPC_ID,
    bedrock_model_ids=BEDROCK_MODELS,
    bedrock_region=REGION,
    image_tag=os.environ.get("IMAGE_TAG", "latest"),
    desired_count=int(os.environ.get("DESIRED_COUNT", "1")),
    user_pool=auth.user_pool,
    user_pool_client_id=auth.app_client.user_pool_client_id,
    hosted_ui_domain=hosted_ui_domain,
    agentcore_runtime_arn=os.environ.get("AGENTCORE_RUNTIME_ARN"),
    agentcore_vision_arn=os.environ.get("AGENTCORE_VISION_ARN"),
    agentcore_ocr_arn=os.environ.get("AGENTCORE_OCR_ARN"),
    agentcore_fusion_arn=os.environ.get("AGENTCORE_FUSION_ARN"),
    agentcore_summary_arn=os.environ.get("AGENTCORE_SUMMARY_ARN"),
    agentcore_memory_id=os.environ.get("BEDROCK_AGENTCORE_MEMORY_ID"),
    agentcore_harness_arn=os.environ.get("AGENTCORE_HARNESS_ARN"),
    tags={"project": "pnid-demo", "tier": "app"},
)
if network:
    app_stack.add_dependency(network)
app_stack.add_dependency(auth)

# ---- cdk-nag suppressions (each one cites the load-bearing reason) -----

NagSuppressions.add_stack_suppressions(
    app_stack,
    [
        {
            "id": "AwsSolutions-IAM4",
            "reason": (
                "ECS task execution role uses the AWS-managed "
                "AmazonECSTaskExecutionRolePolicy by design — switching to "
                "a custom inline policy duplicates the managed policy's "
                "exact set of ECR/CloudWatch permissions without benefit."
            ),
        },
        {
            "id": "AwsSolutions-IAM5",
            "reason": (
                "Wildcards retained on bedrock:ListFoundationModels / "
                "ListInferenceProfiles (read-only discovery actions whose "
                "scope is the entire model catalog) and on log-group "
                "PutRetentionPolicy auto-generated by aws-logs. "
                "InvokeModel calls are scoped per-model in the policy."
            ),
        },
        {
            "id": "AwsSolutions-ELB2",
            "reason": (
                "ALB is private (CloudFront prefix list only); access "
                "logging is intentionally deferred to demo budget and is "
                "covered by VPC flow logs + CloudFront access logs."
            ),
        },
        {
            "id": "AwsSolutions-CFR1",
            "reason": (
                "Geo-restriction is not configured for the demo; the "
                "audience is a regional roadshow and access is gated by "
                "CloudFront's session URL only."
            ),
        },
        {
            "id": "AwsSolutions-CFR2",
            "reason": (
                "WAFv2 is intentionally deferred for this demo. "
                "Production deployments should enable WebACL with managed "
                "AWS Bot Control + IP rate limiting."
            ),
        },
        {
            "id": "AwsSolutions-CFR3",
            "reason": (
                "CloudFront access logging is omitted for the demo to "
                "avoid an extra S3 bucket; CloudWatch L2 dashboards are "
                "sufficient for the recording window."
            ),
        },
        {
            "id": "AwsSolutions-CFR4",
            "reason": (
                "Origin uses HTTP because TLS terminates at CloudFront. "
                "End-to-end TLS would require an ACM cert + custom domain "
                "which is out of scope for the demo."
            ),
        },
        {
            "id": "AwsSolutions-CFR5",
            "reason": (
                "Origin uses HTTP-only by design (see CFR4); origin SSL "
                "protocol setting therefore does not apply. Viewer side "
                "is locked to TLS 1.2_2021 via minimum_protocol_version."
            ),
        },
        {
            "id": "AwsSolutions-ECS2",
            "reason": (
                "Only AWS_REGION is set as a plain env var — it is not a "
                "secret and is needed before the container can authenticate "
                "to Secrets Manager. Sensitive demo settings (e.g. memory "
                "ID) are injected via task-def overrides at deploy time."
            ),
        },
        {
            "id": "AwsSolutions-L1",
            "reason": (
                "Lambda@Edge limits supported runtimes to Node 18 / 20 — "
                "Node 22 is rejected at deploy time. We pin to NODEJS_20_X "
                "even though cdk-nag flags it as not-latest."
            ),
        },
        {
            "id": "AwsSolutions-EC23",
            "reason": (
                "ALB ingress on port 80 is restricted to the CloudFront "
                "managed prefix list pl-82a045eb (us-east-1) only — "
                "0.0.0.0/0 is explicitly excluded via add_listener(open=False)."
            ),
        },
    ],
)

NagSuppressions.add_stack_suppressions(
    auth,
    [
        {
            "id": "AwsSolutions-COG8",
            "reason": (
                "Cognito 'Plus' feature plan ($0.05/MAU + setup) is "
                "rejected for a demo with <10 presenter accounts. "
                "Standard tier with AUDIT-only threat protection is "
                "sufficient for the cost/risk profile."
            ),
        },
        {
            "id": "AwsSolutions-COG2",
            "reason": (
                "MFA is OPTIONAL not REQUIRED — presenter convenience "
                "during a live demo. Tighten to required for production."
            ),
        },
        {
            "id": "AwsSolutions-COG3",
            "reason": (
                "AdvancedSecurityMode replacement (StandardThreatProtectionMode) "
                "set to AUDIT_ONLY because demo budget rejects the Plus tier "
                "needed for ENFORCED mode."
            ),
        },
    ],
)

if network:
  NagSuppressions.add_stack_suppressions(
    network,
    [
        {
            "id": "AwsSolutions-VPC7",
            "reason": "Flow logs are configured on the VPC at construction.",
        },
        {
            "id": "CdkNagValidationFailure",
            "reason": (
                "EC23 validation cannot resolve the VPC CIDR intrinsic "
                "(Fn::GetAtt). The endpoint SG is in fact ingress-locked "
                "to vpc.vpc_cidr_block, so this is a tooling limitation, "
                "not a real finding."
            ),
        },
    ],
)

# ---- Showcase: standalone static kiosk (CloudFront + S3 OAC) ----------
# Independent of the VPC/ECS/Cognito plane. Deploy on its own:
#   cd showcase && npm run build
#   cd infra/cdk && AWS_PROFILE=profile2 npx cdk deploy PnidShowcase
showcase = ShowcaseStack(
    app,
    "PnidShowcase",
    env=ENV,
    tags={"project": "pnid-demo", "tier": "showcase"},
)

NagSuppressions.add_stack_suppressions(
    showcase,
    [
        {
            "id": "AwsSolutions-CFR1",
            "reason": (
                "Geo-restriction not configured — regional roadshow kiosk, "
                "access is the unguessable CloudFront domain only."
            ),
        },
        {
            "id": "AwsSolutions-CFR2",
            "reason": (
                "WAFv2 deferred for this static replay-only kiosk (no backend, "
                "no user input reaches a server). Enable WebACL for production."
            ),
        },
        {
            "id": "AwsSolutions-CFR3",
            "reason": (
                "CloudFront access logging omitted to avoid an extra log "
                "bucket for the demo; the kiosk serves only static assets."
            ),
        },
        {
            "id": "AwsSolutions-CFR4",
            "reason": (
                "Viewer is locked to TLS 1.2_2021; the S3 origin via OAC is "
                "reached over the AWS network, so a custom origin TLS policy "
                "does not apply (S3 REST origin)."
            ),
        },
        {
            "id": "AwsSolutions-S1",
            "reason": (
                "Server access logging on the origin bucket is omitted for "
                "the demo; the bucket is private (OAC only) and holds only "
                "public static SPA assets, no sensitive data."
            ),
        },
        {
            "id": "AwsSolutions-IAM4",
            "reason": (
                "The s3-deployment BucketDeployment uses a CDK-managed Lambda "
                "whose role carries the AWS-managed basic execution policy — "
                "standard for the BucketDeployment construct."
            ),
        },
        {
            "id": "AwsSolutions-IAM5",
            "reason": (
                "BucketDeployment's CDK-managed Lambda needs s3:GetObject*/"
                "PutObject* with object-key wildcards on the asset + target "
                "buckets to sync the SPA; this is the construct's intended scope."
            ),
        },
        {
            "id": "AwsSolutions-L1",
            "reason": (
                "The s3-deployment helper Lambda runtime is pinned by the CDK "
                "construct version, not by us; it is a deploy-time-only function."
            ),
        },
    ],
)

cdk.Aspects.of(app).add(AwsSolutionsChecks(verbose=True))
app.synth()
